
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

beian: 

avatar:
  # Replace the default image and set the url here.
  url: /images/favicon-16x16-star.png

# FancyBox is a tool that offers a nice and elegant way to add zooming functionality for images.
# For more information: https://fancyapps.com/fancybox/
fancybox: true

# tocbot is a tool that builds a table of contents from headings in an HTML document.
# For more information: https://github.com/tscanlin/tocbot
tocbot: true

# Show Views / Visitors of the website / page with busuanzi.
# For more information: http://ibruce.info/2015/04/04/busuanzi/
busuanzi:
  enable: true
  site_uv:
    enable: true
  site_pv:
    enable: true
  post_pv:
    enable: true

# Gitalk
# For more information: https://gitalk.github.io
gitalk:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  admin: 

favicon:
  small: /images/favicon-16x16-star.png
  # medium: /images/favicon-32x32-star.png
  # apple_touch_icon: /images/apple-touch-icon-star.png
  # safari_pinned_tab: /images/logo.svg
  #android_manifest: /manifest.json

social:
  github: seriouszyx