
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

beian: 

# FancyBox is a tool that offers a nice and elegant way to add zooming functionality for images.
# For more information: https://fancyapps.com/fancybox/
fancybox: true

# tocbot is a tool that builds a table of contents from headings in an HTML document.
# For more information: https://github.com/tscanlin/tocbot
tocbot: true

# Show Views / Visitors of the website / page with busuanzi.
# For more information: http://ibruce.info/2015/04/04/busuanzi/
busuanzi:
  enable: true
  site_uv:
    enable: true
  site_pv:
    enable: true
  post_pv:
    enable: true